# Generated by Django 3.2.16 on 2022-11-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-04-22'),
            preserve_default=False,
        ),
    ]
